artifacts:
  - name: wallet-ios-demo
    project-type: xcode-ios
    working-directory: .
    build-type: application
    publish-to: []
    config:
      xcode-version: "26.2"
      scheme: "Wallet Demo"
      project: "Wallet.xcodeproj"
      configuration: Release
      enable-code-signing: true
      export-options-var: EXPORT_OPTIONS_BASE64
      macos-version: macos-26
      build-number: ${BUILD_NUMBER}
