# SPDX-FileCopyrightText: 2026 Digg - Agency for digital government
#
# SPDX-License-Identifier: CC0-1.0

version = 1

# Main project files
[[annotations]]
path = [
  "CHANGELOG.md",
  "README.md",
  "docs/DEVELOPMENT.md",
  "REUSE.toml",
  ".gitignore",
  ".mise.toml",
  ".conform.yaml",
  ".yamlfmt.yml",
  ".swift-format",
  "justfile",
  "**/*.xcconfig",
  "**/*.plist",
  "**/*.xcassets/**",
  "**/*.xcstrings",
  "**/*.yml",
  "**/*.yaml",
  "**/*.json",
  "**/*.xcodeproj/**",
  "**/*.xcworkspace/**",
  "**/*.xcscheme",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Digg - Agency for digital government"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "Wallet/Resources/Fonts/Ubuntu-Bold.ttf",
  "Wallet/Resources/Fonts/Ubuntu-Regular.ttf"
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2011, 2022, 2023 Canonical Ltd. Licensed under the Ubuntu Font Licence 1.0"
SPDX-License-Identifier = "Ubuntu-font-1.0"
